version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/common"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
