[package]
name = "betterletter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.3"
env_logger = "0.10.0"
itertools = "0.10.5"
log = "0.4.17"
regex = "1.8.1"
rstest = "0.17.0"
rust-fsm = "0.6.1"
