[package]
name = "betterletters"
version = "0.1.0"
edition = "2021"
authors = ["Alex Povel <rust@alexpovel.de>"]
description = "Substitute alternative, ASCII-only spellings of special characters with their Unicode equivalents."
license-file = "LICENSE"
repository = "https://github.com/alexpovel/betterletters"
readme = "README.md"
documentation = "https://docs.rs/betterletters"
keywords = ["spelling", "umlaut", "substitute", "unicode", "alternative"]
categories = [
    "accessibility",
    "internationalization",
    "localization",
    "text-processing",
    "value-formatting",
]

[dependencies]
cached = "0.44.0"
clap = { version = "4.4.0", features = ["derive", "env"] }
env_logger = "0.10.0"
itertools = "0.11.0"
log = "0.4.20"
unicode_titlecase = "2.2.1"
fst = "0.4.7"
once_cell = "1.18.0"
decompound = "0.3.0"
regex = "1.9.5"
tree-sitter = "0.20.10"
tree-sitter-python = "0.20.4"
fancy-regex = "0.11.0"

[features]
default = ["all"]
all = ["german", "symbols", "deletion", "squeeze", "upper", "lower", "replace"]
german = []
symbols = []
deletion = []
squeeze = []
upper = []
lower = []
replace = []

[dev-dependencies]
assert_cmd = "2.0.12"
criterion = { version = "0.5.1", features = ["html_reports"] }
insta = { version = "1.31.0", features = ["yaml"] }
paste = "1.0.14"
rstest = "0.18.2"
serde = { version = "1.0.188", features = ["derive"] }
glob = "0.3.1"
num_cpus = "1.16.0"
rand = "0.8.5"
rand_regex = "0.16.0"
test-log = "0.2.12"
proptest = "1.2.0"
enum-iterator = "1.4.1"
serial_test = "2.0.0"
comrak = "0.18.0"
nom = "7.1.3"

[profile.dev.package.insta]
# https://insta.rs/docs/quickstart/#optional-faster-runs
opt-level = 3

[profile.dev.package.similar]
# https://insta.rs/docs/quickstart/#optional-faster-runs
opt-level = 3

[build-dependencies]
cc = { version = "1.0.83", features = ["parallel"] }
decompound = "0.3.0"
fst = "0.4.7"
rayon = "1.7.0"
